name: hs-app-template
version: '1.0.0'
category: Services
author: Arbor Networks
maintainer: mayhem@arbor.net
copyright: Arbor Networks
license: MIT
homepage: https://github.com/packetloop/hs-app-template#readme
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- TupleSections
- MultiParamTypeClasses
dependencies:
- base >=4.7 && <5
- amazonka
- amazonka-core
- amazonka-s3
- avro
- bifunctors
- bytestring
- conduit
- conduit-combinators
- containers
- datadog
- directory
- exceptions
- fast-logger
- hs-arbor-logger
- hw-conduit
- hw-kafka-avro
- hw-kafka-client
- hw-kafka-conduit
- lens
- monad-control
- monad-logger
- mtl
- network
- random
- resourcet
- text
- transformers
- transformers-base
library:
  source-dirs: src
  default-extensions:
  - LambdaCase
  ghc-options: -Wall
  exposed-modules:
  - App
  - App.AWS.Env
  - App.AWS.S3
  - App.AppEnv
  - App.AppError
  - App.AppState
  - App.Application
  - App.Kafka
  - App.Options
  - App.Orphans
  - App.Service
  dependencies:
  - conduit-extra
  - http-types
  - optparse-applicative
  - split
  when:
  - condition: os(osx)
    cpp-options:
    - -D__attribute__(A)=
    - -D_Nullable=
    - -D_Nonnull=
executables:
  hs-app-template:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - LambdaCase
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    dependencies:
    - hs-app-template
    - etc
    - optparse-applicative
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
tests:
  tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - hs-app-template
    - hspec
    - hedgehog
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
